//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUno.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Colaborador
    {
        [Display(Name = "Cedula")]
        public int Cedula { get; set; }
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Display(Name = "Primer Apellido")]
        public string Apellido1 { get; set; }
        [Display(Name = "Segundo Apellido")]
        public string Apellido2 { get; set; }
        [Display(Name = "Fecha de registro")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString ="{0:yyyu/MM/dd}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Registro { get; set; }
        [Display(Name = "Estado")]
        public string Estado { get; set; }
    }
}
